version: 2
jobs:
  build:
    docker:
      - image: rust:1.37

    steps:
      - checkout

      - run:
          name: Update apt index
          command: apt update

      - run:
          name: Install pip3
          command: apt install -y python3-pip

      - run:
          name: Install awscli
          command: pip3 install awscli

      - restore_cache:
          keys:
            - cargo-cache

      - run:
          name: Install mdbook
          command: cargo install mdbook

      - run:
          name: Build HTML files
          command: mdbook build

      - run:
          name: Upload HTML files to S3
          command: aws s3 --delete sync book/ s3://ssh-textbook.keichi.net

      - save_cache:
          key: cargo-cache
          paths:
            - "~/.cargo"
